### ISSUE TITLE
当mysql超过最大连接时间后，会出现 server has gone away， 还有一个问题就是 使用这个orm的时候 发现和mysql不同步

### ISSUE THREAD

**Issue by jinand10** [zqhong/fastd-eloquent#2]
具体描述 是 比如insert 一条数据 返回ID 是会一直自增的  但是mysql 并没有自增成功

**Comment by zqhong** [comment]
> 问题2： 使用这个orm的时候 发现和mysql不同步

具体描述 是 比如insert 一条数据 返回ID 是会一直自增的 但是mysql 并没有自增成功

```sql
show create table `table_name`
```

这个的返回结果是什么？

**Comment by zqhong** [comment]
> 问题1：当mysql超过最大连接时间后，会出现 server has gone away

## 解决方法1
使用持久连接，参考：https://www.php.net/manual/zh/pdo.connections.php

配置 db 的时候，加下下面的设置就行：
```php
            'options' => [
                PDO::ATTR_PERSISTENT => true,
            ],
```

## 解决方法2
使用 MySQL 中间件（MySQL Proxy），比如

* [Atlas](https://github.com/Qihoo360/Atlas)
* [kingshard](https://github.com/flike/kingshard)
* [SMProxy](https://github.com/louislivi/SMProxy)

这里 `SMProxy` 的功能比较纯粹，如果你们不需要实现其他功能，比较合适。
但是我也没有使用过 `SMProxy`，需要你们自己测试。

**Comment by zqhong** [comment]
> 问题2： 使用这个orm的时候 发现和mysql不同步

具体描述 是 比如insert 一条数据 返回ID 是会一直自增的 但是mysql 并没有自增成功

```sql
show create table `table_name`
```

这个的返回结果是什么？
